server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:\Users\User\Desktop\Coding\inflearn\SpringCloud\git-local-repo
          uri: file://C:\Users\choi\Desktop\Choi\coding\inflearn\springCloud\git-local-repo
